package form;

import data.Fotovoltaico;
import data.FotovoltaicoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class ListaFotovoltaico extends javax.swing.JFrame {

    private String permissao;
    
    private void preencherTabela() {
        FotovoltaicoDAO fotovoltaicoDao = new FotovoltaicoDAO();
        
        List<Fotovoltaico> listaFotovoltaico = fotovoltaicoDao.getFV();

        DefaultTableModel tabelafv = (DefaultTableModel) tblFotovoltaico.getModel();
        tabelafv.setNumRows(0);

        tblFotovoltaico.setRowSorter(new TableRowSorter(tabelafv));

        for (Fotovoltaico c : listaFotovoltaico) {
            Object[] obj = new Object[]{
                c.getId(),
                c.getFabricante(),
                c.getQtdPlacas(),
                c.getPotPlacas(),
                c.getPotGerador(),
                c.getPotInversor(),
                c.getTipoTelhado(),
                c.getConcessionariaEnergia(),
                c.getCliente_id().getNome(),};
            tabelafv.addRow(obj);
        }

    }

    public ListaFotovoltaico() {
        initComponents();
        preencherTabela();
    }

    public int getPosicaoFV() {
        int posUser = tblFotovoltaico.getSelectedRow();

        if (posUser == -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um usuário");
        }

        return posUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbFotovoltaico = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFotovoltaico = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista Fotovoltaico");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbFotovoltaico.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbFotovoltaico.setForeground(new java.awt.Color(20, 105, 205));
        lbFotovoltaico.setText("Lista Fotovoltaico");

        tblFotovoltaico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fabricante", "Qtd Placas", "Potência Placas", "Potência Gerador", "Potência Inversor", "Tipo de Telhado", "Concessionária", "Cliente"
            }
        ));
        jScrollPane1.setViewportView(tblFotovoltaico);

        btnEditar.setBackground(new java.awt.Color(186, 216, 251));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(20, 105, 205));
        btnEditar.setText("Alterar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(lbFotovoltaico)
                        .addGap(0, 400, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(btnEditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbFotovoltaico)
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnEditar)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        TelaCadastroFotovoltaico telaCadastro = new TelaCadastroFotovoltaico();
        int posUser = tblFotovoltaico.getSelectedRow();
        if (posUser >= 0) { // Verifica se há linha selecionada na tabela
            int idCliente = (int) tblFotovoltaico.getValueAt(posUser, 0);
            telaCadastro.PegaIDcliente(idCliente); // Passa o usuário selecionado para a tela de cadastro
            dispose();
            telaCadastro.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaFotovoltaico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaFotovoltaico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaFotovoltaico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaFotovoltaico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaFotovoltaico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbFotovoltaico;
    private javax.swing.JTable tblFotovoltaico;
    // End of variables declaration//GEN-END:variables


    public void validaPermissao(String permissao) {
        
        if (permissao.equals("Projetista")) {
            btnEditar.setEnabled(false);
        } else if (permissao.equals("Vendedor")) {
            btnEditar.setEnabled(false);
        }
    }
}
