package form;

import data.Clientes;
import data.ClientesDAO;
import javax.swing.JOptionPane;

public class TelaCadastroCliente extends javax.swing.JFrame {

    private String permissao;

    public TelaCadastroCliente() {
        initComponents();       
    }

    public TelaCadastroCliente(String permissao) {
        this.permissao = permissao;
        // Resto do código do construtor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbCadastrarCliente = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        lbNum = new javax.swing.JLabel();
        lbComplemento = new javax.swing.JLabel();
        lbBairro = new javax.swing.JLabel();
        lbCidade = new javax.swing.JLabel();
        lbUf = new javax.swing.JLabel();
        lbCep = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbTelefone = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtNum = new javax.swing.JTextField();
        txtComplemento = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtUF = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        rdbCPF = new javax.swing.JRadioButton();
        rdbCNPJ = new javax.swing.JRadioButton();
        fmtxtCPF = new javax.swing.JFormattedTextField();
        fmtxtCNPJ = new javax.swing.JFormattedTextField();
        btnListaClientes = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        lbID = new javax.swing.JLabel();
        txtPesquisaID = new javax.swing.JTextField();
        btnPesquisarID = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Cadastrar Cliente");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbCadastrarCliente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbCadastrarCliente.setForeground(new java.awt.Color(20, 105, 205));
        lbCadastrarCliente.setText("Cadastrar Cliente");

        lbNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNome.setText("Nome:");

        lbEndereco.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbEndereco.setText("Endereço:");

        lbNum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNum.setText("Número:");

        lbComplemento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbComplemento.setText("complemento:");

        lbBairro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbBairro.setText("Bairro:");

        lbCidade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCidade.setText("Cidade:");

        lbUf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbUf.setText("UF:");

        lbCep.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCep.setText("CEP:");

        lbEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbEmail.setText("e-mail:");

        lbTelefone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTelefone.setText("Telefone:");

        txtNome.setToolTipText("Nome Completo");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtEndereco.setToolTipText("Endereço");
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        txtNum.setToolTipText("Número da Residência");

        txtComplemento.setToolTipText("Complemento");
        txtComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoActionPerformed(evt);
            }
        });

        txtBairro.setToolTipText("Bairro");

        txtCidade.setToolTipText("Cidade");

        txtUF.setToolTipText("Unidade Federativa");

        txtCep.setToolTipText("CEP");
        txtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCepActionPerformed(evt);
            }
        });

        txtEmail.setToolTipText("E-mail");
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtTelefone.setToolTipText("Telefone");

        btnCadastrar.setBackground(new java.awt.Color(186, 216, 251));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(20, 105, 205));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(251, 209, 186));
        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(20, 105, 205));
        btnLimpar.setText("Limpar");
        btnLimpar.setToolTipText("Limpa os campos formuário");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        rdbCPF.setText("CPF");
        rdbCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCPFActionPerformed(evt);
            }
        });

        rdbCNPJ.setText("CNPJ");
        rdbCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCNPJActionPerformed(evt);
            }
        });

        try {
            fmtxtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fmtxtCPF.setToolTipText("CPF");

        try {
            fmtxtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fmtxtCNPJ.setToolTipText("CNPJ");

        btnListaClientes.setBackground(new java.awt.Color(186, 216, 251));
        btnListaClientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnListaClientes.setForeground(new java.awt.Color(20, 105, 205));
        btnListaClientes.setText("Lista de Clientes");
        btnListaClientes.setToolTipText("Abre Tela Listagem");
        btnListaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaClientesActionPerformed(evt);
            }
        });

        btnAtualizar.setBackground(new java.awt.Color(186, 216, 251));
        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(20, 105, 205));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        lbID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbID.setText("ID:");

        btnPesquisarID.setBackground(new java.awt.Color(186, 216, 251));
        btnPesquisarID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPesquisarID.setForeground(new java.awt.Color(20, 105, 205));
        btnPesquisarID.setText("Pesquisar");
        btnPesquisarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarIDActionPerformed(evt);
            }
        });

        txtID.setEditable(false);

        btnExcluir.setBackground(new java.awt.Color(251, 209, 186));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(204, 0, 0));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(lbCadastrarCliente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbEndereco)
                                            .addComponent(lbNum)
                                            .addComponent(lbBairro)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbEmail)
                                                .addComponent(lbCidade)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(lbComplemento)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnListaClientes))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(txtEmail)
                                                            .addComponent(txtCidade)
                                                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(lbUf)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtUF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(lbTelefone))))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(21, 21, 21)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(txtTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(lbCep)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(32, 32, 32)
                                                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPesquisaID, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(btnPesquisarID)
                                        .addGap(301, 301, 301))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(12, 12, 12)
                                .addComponent(btnExcluir))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(rdbCPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fmtxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdbCNPJ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fmtxtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbCadastrarCliente)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbID)
                    .addComponent(txtPesquisaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbCPF)
                    .addComponent(rdbCNPJ)
                    .addComponent(fmtxtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fmtxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNum)
                    .addComponent(lbComplemento)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCidade)
                    .addComponent(lbUf)
                    .addComponent(lbCep)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTelefone)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbEmail)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoActionPerformed

    private void txtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCepActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void rdbCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCPFActionPerformed

        if (evt.getSource() == rdbCPF) {
            rdbCNPJ.setSelected(false);
            fmtxtCPF.setEditable(true);
            fmtxtCNPJ.setEditable(false);
            fmtxtCNPJ.setText("");

            if (!rdbCPF.isSelected()) {
                fmtxtCPF.setText("");
            }
        }
    }//GEN-LAST:event_rdbCPFActionPerformed

    private void rdbCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCNPJActionPerformed
        if (evt.getSource() == rdbCNPJ) {
            rdbCPF.setSelected(false);
            fmtxtCNPJ.setEditable(true);
            fmtxtCPF.setEditable(false);
            fmtxtCPF.setText("");

            if (!rdbCNPJ.isSelected()) {
                fmtxtCNPJ.setText("");
            }
        }
    }//GEN-LAST:event_rdbCNPJActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        LimparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (!emptyFields()) {
            String nome = txtNome.getText();
            String endereco = txtEndereco.getText();
            String numero = txtNum.getText();
            String complemento = txtComplemento.getText();
            String bairro = txtBairro.getText();
            String cidade = txtCidade.getText();
            String uf = txtUF.getText();
            String cep = txtCep.getText();
            String email = txtEmail.getText();
            String telefone = txtTelefone.getText();
            String cpf_cnpj = "";

            if (rdbCPF.isSelected()) {
                cpf_cnpj = fmtxtCPF.getText();
            } else if (rdbCNPJ.isSelected()) {
                cpf_cnpj = fmtxtCNPJ.getText();
            }

            Clientes cliente = new Clientes();

            cliente.setNome(nome);
            cliente.setCpf_cnpj(cpf_cnpj);
            cliente.setEndereco(endereco);
            cliente.setNumero(numero);
            cliente.setComplemento(complemento);
            cliente.setBairro(bairro);
            cliente.setCidade(cidade);
            cliente.setUF(uf);
            cliente.setCep(cep);
            cliente.setEmail(email);
            cliente.setTelefone(telefone);

            ClientesDAO clienteDao = new ClientesDAO();
            clienteDao.inserirCliente(cliente);

            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
            LimparCampos();
        }


    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaClientesActionPerformed
        TelaListagem listagem = new TelaListagem();
        listagem.validaPermissao(permissao);
        dispose();
        listagem.setVisible(true);
    }//GEN-LAST:event_btnListaClientesActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        if (!emptyFields()) {
            int id = Integer.parseInt(txtID.getText());
            String nome = txtNome.getText();
            String endereco = txtEndereco.getText();
            String numero = txtNum.getText();
            String complemento = txtComplemento.getText();
            String bairro = txtBairro.getText();
            String cidade = txtCidade.getText();
            String uf = txtUF.getText();
            String cep = txtCep.getText();
            String email = txtEmail.getText();
            String telefone = txtTelefone.getText();
            String cpf_cnpj = "";

            if (rdbCPF.isSelected()) {
                cpf_cnpj = fmtxtCPF.getText();
            } else if (rdbCNPJ.isSelected()) {
                cpf_cnpj = fmtxtCNPJ.getText();
            }

            Clientes cliente = new Clientes();

            cliente.setId(id);
            cliente.setNome(nome);
            cliente.setCpf_cnpj(cpf_cnpj);
            cliente.setEndereco(endereco);
            cliente.setNumero(numero);
            cliente.setComplemento(complemento);
            cliente.setBairro(bairro);
            cliente.setCidade(cidade);
            cliente.setUF(uf);
            cliente.setCep(cep);
            cliente.setEmail(email);
            cliente.setTelefone(telefone);

            ClientesDAO clienteDao = new ClientesDAO();
            clienteDao.editar(cliente);

            JOptionPane.showMessageDialog(null, "Cadastro atualizado com sucesso!");
            LimparCampos();
        }

    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnPesquisarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarIDActionPerformed

        if (txtPesquisaID.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe um ID");
        } else {
            int idPesquisa = Integer.parseInt(txtPesquisaID.getText());
            ClientesDAO clienteDao = new ClientesDAO();
            Clientes cliente = clienteDao.getClientes(idPesquisa);

            if (cliente == null) {
                JOptionPane.showMessageDialog(this, "Cliente não encontrado!");
            } else {
                txtID.setText(String.valueOf(cliente.getId()));
                txtNome.setText(cliente.getNome());
                txtEndereco.setText(cliente.getEndereco());
                txtNum.setText(cliente.getNumero());
                txtComplemento.setText(cliente.getComplemento());
                txtBairro.setText(cliente.getBairro());
                txtCidade.setText(cliente.getCidade());
                txtUF.setText(cliente.getUF());
                txtCep.setText(cliente.getCep());
                txtEmail.setText(cliente.getEmail());
                txtTelefone.setText(cliente.getTelefone());

                fmtxtCPF.setText(cliente.getCpf_cnpj());
                fmtxtCNPJ.setText(cliente.getCpf_cnpj());

                String cpf_cnpj = cliente.getCpf_cnpj();

                if (cpf_cnpj != null) {
                    if (cpf_cnpj.length() == 14) { // CPF possui 11 dígitos
                        rdbCPF.setSelected(true);
                        rdbCNPJ.setSelected(false);
                        fmtxtCNPJ.setEditable(false);
                    } else if (cpf_cnpj.length() == 18) { // CNPJ possui 14 dígitos
                        rdbCPF.setSelected(false);
                        rdbCNPJ.setSelected(true);
                        fmtxtCPF.setEditable(false);
                    } else {
                        rdbCPF.setSelected(false);
                        rdbCNPJ.setSelected(false);
                    }
                } else {
                    rdbCPF.setSelected(false);
                    rdbCNPJ.setSelected(false);
                }
            }
        }
    }//GEN-LAST:event_btnPesquisarIDActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int id = Integer.parseInt(txtID.getText());

        ClientesDAO clienteDao = new ClientesDAO();
        clienteDao.Excluir(id);

        LimparCampos();
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnListaClientes;
    private javax.swing.JButton btnPesquisarID;
    private javax.swing.JFormattedTextField fmtxtCNPJ;
    private javax.swing.JFormattedTextField fmtxtCPF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbCadastrarCliente;
    private javax.swing.JLabel lbCep;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbComplemento;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNum;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JLabel lbUf;
    private javax.swing.JRadioButton rdbCNPJ;
    private javax.swing.JRadioButton rdbCPF;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtPesquisaID;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtUF;
    // End of variables declaration//GEN-END:variables

    public void LimparCampos() {

        txtPesquisaID.setText("");
        txtID.setText("");
        txtNome.setText("");
        txtEndereco.setText("");
        txtNum.setText("");
        txtComplemento.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtUF.setText("");
        txtCep.setText("");
        txtEmail.setText("");
        txtTelefone.setText("");
        fmtxtCPF.setText("");
        fmtxtCNPJ.setText("");
        rdbCPF.setSelected(false);
        rdbCNPJ.setSelected(false);

    }

    private boolean emptyFields() {

        boolean empty = true;

        if (txtNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Nome não pode ser vazio.");
        } else if (fmtxtCPF.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! CPF não pode ser vazio.");
        } else if (fmtxtCNPJ.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! CNPJ não pode ser vazio.");
        } else if (txtEndereco.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Endereço não pode ser vazio.");
        } else if (txtNum.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Número não pode ser vazio.");
        } else if (txtBairro.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Bairro não pode ser vazio.");
        } else if (txtCidade.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Cidade não pode ser vazio.");
        } else if (txtUF.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! UF não pode ser vazio.");
        } else if (txtCep.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! CEP não pode ser vazio.");
        } else if (txtEmail.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Email não pode ser vazio.");
        } else if (txtTelefone.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Telefone não pode ser vazio.");
        } else {
            empty = false;
        }
        return empty;
    }

    public void PegaIDcliente(int idCliente) {
        // Preencha os campos da tela de cadastro com o ID do cliente
        txtPesquisaID.setText(String.valueOf(idCliente));
    }

    public void validaPermissao(String permissao) {
        this.permissao = permissao;
        if (permissao.equals("Projetista")) {
            btnCadastrar.setEnabled(false);
            btnAtualizar.setEnabled(false);
            btnExcluir.setEnabled(false);
        } else if (permissao.equals("Vendedor")) {
            btnAtualizar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
    }
}
