package form;

public class TelaLogada extends javax.swing.JFrame {

    private String permissao;

    public TelaLogada() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbBemvindo = new javax.swing.JLabel();
        lbOpcoes = new javax.swing.JLabel();
        btnCadastrarUsuario = new javax.swing.JButton();
        btnCadastroCliente = new javax.swing.JButton();
        btnCadastrarFotovoltaico = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnListaFV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Bem Vindo");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(20, 105, 205));

        lbBemvindo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbBemvindo.setForeground(new java.awt.Color(20, 105, 205));
        lbBemvindo.setText("Bem-vindo!");

        lbOpcoes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbOpcoes.setText("Selecione uma opção para navegar pelo Portal.");

        btnCadastrarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrarUsuario.setForeground(new java.awt.Color(20, 105, 205));
        btnCadastrarUsuario.setText("Cadastrar Novo Usuário");
        btnCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarUsuarioActionPerformed(evt);
            }
        });

        btnCadastroCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastroCliente.setForeground(new java.awt.Color(20, 105, 205));
        btnCadastroCliente.setText("Cadastrar Cliente");
        btnCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroClienteActionPerformed(evt);
            }
        });

        btnCadastrarFotovoltaico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrarFotovoltaico.setForeground(new java.awt.Color(20, 105, 205));
        btnCadastrarFotovoltaico.setText("Cadastrar Fotovoltaico");
        btnCadastrarFotovoltaico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFotovoltaicoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(20, 105, 205));
        jButton1.setText("Listagem de Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnListaFV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListaFV.setForeground(new java.awt.Color(20, 105, 205));
        btnListaFV.setText("Listagem de Fotovoltaico");
        btnListaFV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaFVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lbOpcoes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(lbBemvindo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListaFV)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnCadastrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCadastroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCadastrarFotovoltaico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbBemvindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbOpcoes)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnCadastroCliente)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarFotovoltaico)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(btnListaFV)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUsuarioActionPerformed
        // TODO add your handling code here:
        TelaCadastrarUsuario cadastroUsuario = new TelaCadastrarUsuario();
        cadastroUsuario.validaPermissao(permissao);
        cadastroUsuario.setVisible(true);
    }//GEN-LAST:event_btnCadastrarUsuarioActionPerformed

    private void btnCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroClienteActionPerformed
        TelaCadastroCliente cadastraCliente = new TelaCadastroCliente();
        cadastraCliente.validaPermissao(permissao);
        cadastraCliente.setVisible(true);
    }//GEN-LAST:event_btnCadastroClienteActionPerformed

    private void btnCadastrarFotovoltaicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFotovoltaicoActionPerformed
        TelaCadastroFotovoltaico cadastrarFV = new TelaCadastroFotovoltaico();
        cadastrarFV.validaPermissao(permissao);
        cadastrarFV.setVisible(true);
    }//GEN-LAST:event_btnCadastrarFotovoltaicoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaListagem listagem = new TelaListagem();
        listagem.validaPermissao(permissao);
        listagem.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnListaFVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaFVActionPerformed
       ListaFotovoltaico listagemFV = new ListaFotovoltaico();
       listagemFV.validaPermissao(permissao);
        listagemFV.setVisible(true);
    }//GEN-LAST:event_btnListaFVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarFotovoltaico;
    private javax.swing.JButton btnCadastrarUsuario;
    private javax.swing.JButton btnCadastroCliente;
    private javax.swing.JButton btnListaFV;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBemvindo;
    private javax.swing.JLabel lbOpcoes;
    // End of variables declaration//GEN-END:variables

    public void validaPermissao(String permissao) {
        this.permissao = permissao;
        if (permissao.equals("Projetista")) {
            btnCadastrarUsuario.setEnabled(false);
            btnCadastroCliente.setEnabled(false);
            btnCadastrarFotovoltaico.setEnabled(false);
        } else if (permissao.equals("Vendedor")) {
            btnCadastrarUsuario.setEnabled(false);
        }
    }

}
