package form;

import data.Clientes;
import data.ClientesDAO;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class TelaListagem extends javax.swing.JFrame {

      
    private String permissao;
    

    private void preencherTabela() {
        ClientesDAO clienteDao = new ClientesDAO();
        String nomeCliente = txtPesquisaNome.getText();
        List<Clientes> listaClientes = clienteDao.getCliente(nomeCliente);

        DefaultTableModel tabelaClientes = (DefaultTableModel) tblListaClientes.getModel();
        tabelaClientes.setNumRows(0);

        tblListaClientes.setRowSorter(new TableRowSorter(tabelaClientes));

        for (Clientes c : listaClientes) {
            Object[] obj = new Object[]{
                c.getId(),
                c.getNome(),
                c.getCpf_cnpj(),
                c.getEndereco(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
                c.getCidade(),
                c.getUF(),
                c.getCep(),
                c.getEmail(),
                c.getTelefone()
            };
            tabelaClientes.addRow(obj);
        }

    }

    /**
     * Creates new form TelaListagem
     */
    public TelaListagem() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbListagem = new javax.swing.JLabel();
        lbPesquisaNome = new javax.swing.JLabel();
        txtPesquisaNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaClientes = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnFotovoltaico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Listagem");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbListagem.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbListagem.setForeground(new java.awt.Color(20, 105, 205));
        lbListagem.setText("Listagem Clientes");

        lbPesquisaNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbPesquisaNome.setText("Pesquisa por nome:");

        txtPesquisaNome.setToolTipText("Clique enter para filtrar");
        txtPesquisaNome.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisaNomeCaretUpdate(evt);
            }
        });
        txtPesquisaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaNomeActionPerformed(evt);
            }
        });

        tblListaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF ou CNPJ", "Endereço", "Numero", "Complemento", "Bairro", "Cidade", "UF", "CEP", "Email", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(tblListaClientes);

        btnEditar.setBackground(new java.awt.Color(186, 216, 251));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(20, 105, 205));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnFotovoltaico.setBackground(new java.awt.Color(186, 216, 251));
        btnFotovoltaico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFotovoltaico.setForeground(new java.awt.Color(20, 105, 205));
        btnFotovoltaico.setText("Cadastrar Fotovoltaico");
        btnFotovoltaico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotovoltaicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbPesquisaNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(lbListagem)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFotovoltaico)
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbListagem)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPesquisaNome)
                    .addComponent(txtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar)
                    .addComponent(btnFotovoltaico))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaNomeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtPesquisaNomeActionPerformed

    private void txtPesquisaNomeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisaNomeCaretUpdate
        preencherTabela();
    }//GEN-LAST:event_txtPesquisaNomeCaretUpdate

    private void btnFotovoltaicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotovoltaicoActionPerformed
        TelaCadastroFotovoltaico cadastrarFV = new TelaCadastroFotovoltaico();        
        int posUser = tblListaClientes.getSelectedRow();
        if (posUser >= 0) {
            int idCliente = (int) tblListaClientes.getValueAt(posUser, 0);
            cadastrarFV.PegaIDclienteFK(idCliente);
            dispose();
            cadastrarFV.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente");
        }
    }//GEN-LAST:event_btnFotovoltaicoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        TelaCadastroCliente telaCadastro = new TelaCadastroCliente();
        
        int posUser = tblListaClientes.getSelectedRow();
        if (posUser >= 0) { // Verifica se há linha selecionada na tabela
            int idCliente = (int) tblListaClientes.getValueAt(posUser, 0);
            telaCadastro.PegaIDcliente(idCliente); // Passa o usuário selecionado para a tela de cadastro
            dispose();
            telaCadastro.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListagem.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListagem.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListagem.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListagem.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFotovoltaico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbListagem;
    private javax.swing.JLabel lbPesquisaNome;
    private javax.swing.JTable tblListaClientes;
    private javax.swing.JTextField txtPesquisaNome;
    // End of variables declaration//GEN-END:variables

    public void validaPermissao(String permissao) {
        
        if (permissao.equals("Projetista")) {
            this.permissao = permissao;
            btnEditar.setEnabled(false);
            btnFotovoltaico.setEnabled(false);
           } else if (permissao.equals("Vendedor")) {
            btnEditar.setEnabled(false);
        }
    }   

}
